version: "3.7"
services:
  database:
    image: postgres
    container_name: 'rfid-auth-database'
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports: 
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/data/postgres
    restart: always

volumes:
    pgdata:
        driver: local